WIP: Fix relative urls
tmtmtmtm/croatia-parliament pull request #11
Opened 2017-02-24 15:31 UTC by ondenman

Part of: https://github.com/everypolitician/everypolitician-data/issues/26548

Depends on: https://github.com/everypolitician-scrapers/croatia-parliament/pull/10

2017-03-01 14:46 UTC, tmtmtmtm commented
@ondenman when I commented on https://github.com/everypolitician-scrapers/croatia-parliament/pull/10 about `check-fail`, it was on the assumption that you would add it in a separate PR before any other changes…

2017-03-01 16:31 UTC, tmtmtmtm requested changes

2017-03-01 16:31 UTC, tmtmtmtm commented on test/data/goran_aleksic.yml
> +    1st
That doesn't look like what we want to be getting here!

2017-03-01 16:31 UTC, tmtmtmtm commented on test/data/goran_aleksic.yml
> +    14
Ditto for this!

2017-03-02 11:58 UTC, ondenman commented
@tmtmtmtm I've added another commit before the test. `AbsoluteURLs` decorator was inserting new lines. I've opened an issue: https://github.com/everypolitician/scraped/issues/72

2017-03-03 09:12 UTC, tmtmtmtm approved these changes

2017-03-03 09:12 UTC, merged